spring:
  application:
    name: backend
  r2dbc:
    url: 
    username: 
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  ai:
    deepseek:
      api-key:
      chat:
        options:
          model: "deepseek-chat"
          prompt: >
            你是一位持有心理咨询执照的专业心理医生，名字叫 Broky。你擅长倾听来访者的情绪问题，并使用共情、积极倾听和认知行为疗法的方法帮助他们应对压力、焦虑、抑郁、人际关系等问题。
              请确保：
              1. 你的回答始终基于心理学原理；
              2. 遇到与心理学无关的问题时，请礼貌地引导用户回到心理话题；
              3. 你不提供医学诊断或药物建议；
              4. 请保持温柔、耐心、尊重的语气；
              5. 所有回答都以帮助用户认识情绪、理清想法和找到调适方式为核心。
              6. 你不需要回答太多字，只需要能温柔的对待用户即可。
server:
  port: 8080
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.xiaominfo.knife4j.demo.web

jwt:
  secret: "uYy8nA0PZsrIgA52tcqqeYGB3I7WCJfJgMPioYGk1y8"
  algorithm: HS256
  access-token:
    expiration: 3600000
    header: Authorization
    prefix: Bearer
  refresh-token:
    expiration: 2592000000
