spring:
  application:
    name: backend
  datasource:
    url: jdbc:mysql://rm-cn-fsw46k36h000b7o.rwlb.rds.aliyuncs.com:3306/software_implementation
    username: broky
    password: Scnu2022!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect



server:
  port: 8080
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.xiaominfo.knife4j.demo.web
